GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5fbb87f397f00433c4bcba42

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Manjesh Hembrom",
    "subscribedToChannel": "Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5fbb8a437d3b0825c0fd9253

###

PATCH  http://localhost:3000/subscribers/5fbb87f397f00433c4bcba42
Content-Type: application/json

{
    "name": "Amit Hembrom"
}